{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-blackduck-ui
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - .Values.ingress.tls.host
{{- end }}
  rules:
    - host: {{ tpl .Values.ingress.host . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              service:
                name: {{ .Release.Name }}-blackduck-ui
                port:
                  number: 8443
            pathType: ImplementationSpecific
{{- end }}
